### ISSUE TITLE
The process of your dealing with the raw netflow dataest.

### ISSUE THREAD

**Issue by Henry3II** [amhajavi/RNN_Intrusion_Detection#1]
I'm afraid I didn't understand the process of your dealing with the raw data. The conversion process from raw data to the used data, is it a 'string to integer array'? But how to do this conversion?

**Comment by amhajavi** [comment]
The raw data to feed to the system is the sequences of CVs which are the constants and vowels. It was provided in the dataset since the beginning (distinguished by an expert). 

All I did was to convert the C and V character into their ordinal number of alphabet and feed them as array of numbers to the RNN.

**Comment by Henry3II** [comment]
emmm...Thanks, I understand the data after I learned about ADFA-LD... but I met a new problem: when I run the 'Run.py', it returned:
Epoch 1 error 50.0%
Epoch 2 error 50.0%
Epoch 3 error 50.0%
Epoch 4 error 50.0%
Epoch 5 error 50.0%
Epoch 6 error 50.0%
Epoch 7 error 50.0%
...
What's wrong...

**Comment by amhajavi** [comment]
There is nothing wrong with the output you are getting. It is just saying that up until epoch 7 you are getting an error rate of 50% 

It will decrease on later epochs. If Not you are not getting the right data and there is something wrong with your arrays print them and find out what it is.
